teleop_joy_node:      #name of the node
  ros__parameters:    #parameters to pass to the node executable
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.5

    enable_button: 2  # X button

   #define axis mapping for the teleop_twist_joy node
